services:
  db:
    image: postgres:15
    container_name: marketplace-postgres
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: marketplace_pass
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: marketplace-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marketplace_db
      SPRING_DATASOURCE_USERNAME: marketplace_user
      SPRING_DATASOURCE_PASSWORD: marketplace_pass
    ports:
      - "8080:8080"

volumes:
  db_data:
